CREATE TABLE "order" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"loan_number" varchar(50),
	"loan_officer" varchar(255),
	"loan_officer_email" varchar(255),
	"lender" varchar(255),
	"lender_address" varchar(255),
	"lender_city" varchar(255),
	"lender_zip" varchar(10),
	"borrower_name" varchar(255),
	"borrower_email" varchar(255),
	"borrower_phone_type" varchar(50),
	"borrower_phone_number" varchar(30),
	"property_address" varchar(255),
	"property_city" varchar(255),
	"property_state" varchar(50),
	"property_zip" varchar(10),
	"order_type" varchar(255),
	"property_type" varchar(255),
	"present_occupancy" varchar(255),
	"loan_purpose" varchar(255),
	"loan_type" varchar(255),
	"main_product" varchar(255),
	"requested_due_date" varchar(50),
	"description" text
);
