import { OpenOrder } from "types"

export const SampleOrder: OpenOrder[] = [
      {
        id: 1,
        PropAddress: "123 Main Street",
        PropCity: "Anytown",
        PropOwner: "John Doe",
        PropState: "VA",
        PropZip: "20112",
        Services: "5234",
        UserID: 9283,
        PONumber: "dolore velit sint ea",
        dbaName: "occaecat consectetur",
        PropDesc: "quis ipsum sit cillum enim",
        AccContact: "JANE DOE",
        AccMobile: "+1 (555) 123-4567",
        AccHome: "+1 (555) 987-6543",
        AccWork: "+1 (555) 555-5555",
        AccEmail: "john.doe@example.com",
        CallbackReference: "https://yourapisite.com?id=123456",
        Notes: "quis cupidatat consectetur aute voluptate",
        ReportHTML: "nostrud enim ut adipisicing dolor",
        Status: "Completed",
        isDone: true,
      },
      {
        id: 2,
        PropAddress: "456 Oak Avenue",
        PropCity: "Springfield",
        PropOwner: "Jane Smith",
        PropState: "CA",
        PropZip: "90210",
        Services: "1234",
        UserID: 7823,
        PONumber: "amet nostrud lorem sit",
        dbaName: "consectetur adipiscing",
        PropDesc: "labore magna sint ullamco",
        AccContact: "JANE DOE",
        AccMobile: "+1 (555) 234-5678",
        AccHome: "+1 (555) 876-5432",
        AccWork: "+1 (555) 444-4444",
        AccEmail: "jane.smith@example.com",
        CallbackReference: "https://yourapisite.com?id=654321",
        Notes: "occaecat do dolor occaecat",
        ReportHTML: "consectetur sit elit veniam",
        Status: "Awaiting Vendor Approval",
        isDone: false,
      },
      {
        id: 3,
        PropAddress: "789 Pine Road",
        PropCity: "Lakeside",
        PropOwner: "Alice Green",
        PropState: "TX",
        PropZip: "75001",
        Services: "9876",
        UserID: 2354,
        PONumber: "dolore amet esse eiusmod",
        dbaName: "tempor exercitation ullamco",
        PropDesc: "exercitation pariatur duis nisi",
        AccContact: "JANE DOE",
        AccMobile: "+1 (555) 345-6789",
        AccHome: "+1 (555) 765-4321",
        AccWork: "+1 (555) 333-3333",
        AccEmail: "alice.green@example.com",
        CallbackReference: "https://yourapisite.com?id=789012",
        Notes: "commodo ullamco labore velit",
        ReportHTML: "voluptate laboris minim aute",
        Status: "Awaiting QC",
        isDone: true,
      },
      {
        id: 4,
        PropAddress: "101 Maple Street",
        PropCity: "Riverside",
        PropOwner: "Robert White",
        PropState: "FL",
        PropZip: "33101",
        Services: "4567",
        UserID: 3647,
        PONumber: "deserunt occaecat anim nulla",
        dbaName: "ad minim deserunt",
        PropDesc: "culpa pariatur incididunt qui",
        AccContact: "JANE DOE",
        AccMobile: "+1 (555) 456-7890",
        AccHome: "+1 (555) 654-3210",
        AccWork: "+1 (555) 222-2222",
        AccEmail: "robert.white@example.com",
        CallbackReference: "https://yourapisite.com?id=101010",
        Notes: "sint ullamco pariatur irure",
        ReportHTML: "adipisicing deserunt ex officia", 
        Status: "Awaiting Report from Vendor",
        isDone: true,
      },
      {
        id: 5,
        PropAddress: "202 Birch Lane",
        PropCity: "Centerville",
        PropOwner: "Michael Blue",
        PropState: "NY",
        PropZip: "10001",
        Services: "6789",
        UserID: 9271,
        PONumber: "fugiat laboris velit aute",
        dbaName: "sit ad amet",
        PropDesc: "veniam exercitation labore ipsum",
        AccContact: "JANE DOE",
        AccMobile: "+1 (555) 567-8901",
        AccHome: "+1 (555) 432-1098",
        AccWork: "+1 (555) 111-1111",
        AccEmail: "michael.blue@example.com",
        CallbackReference: "https://yourapisite.com?id=202020",
        Notes: "velit pariatur nostrud aliqua",
        ReportHTML: "eiusmod veniam sunt sint",
        Status: "Awaiting Report from Vendor",
        isDone: false
      }
  ]

  